JJ/IV-17-18

- proyectos/hito-0.md
He actualizado mi línea en el fichero hito-0.md
> Filled my line on hito-0.md

- proyectos/hito-0.md
He creado mi repositorio propio, añadiendo al *fork* del original del profesor un enlace al mío (con la versión correspondiente).
[https://github.com/JJ/IV-17-18/proyectos/hito-0.md](https://github.com/JJ/IV-17-18/proyectos/hito-0.md)
> completado hito-0

- objetivos/JoseGomezBaena.md
- proyectos/hito-0.md
https://github.com/josegob/IV-17-18/blob/master/objetivos/JoseGomezBaena.md
Entregado Hito 0 en el que se explica que se va a realizar como proyecto para la asignatura
https://github.com/josegob/IV-1718-Proyectos
> Commits Hito 0

- objetivos/CristianVelezRuiz.md
- proyectos/hito-0.md
[Objetivos hito 0](https://github.com/ainokila/IV-17-18/blob/master/objetivos/CristianVelezRuiz.md)
* [ X] He leído el guión del hito
* [ X] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [ X] He actualizado con la última versión del fichero de entrega y
* [ X] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
Creados y enlazados los repositorios para el proyecto y los ejercicios.
> Entrega hito 0

- objetivos/GermanCastroMontes.md
- proyectos/hito-0.md
[Objetivos Germán](https://github.com/JJ/IV-17-18/tree/master/objetivos/GermanCastroMontes.md)
* [ X ] He leído el guión del hito
* [ X ] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [ X ] He actualizado con la última versión del fichero de entrega y
* [ X ] Si estoy enviando otra versión porque no pasó los tests la
* [ X ] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
* [ X ] He actualizado con la última versión del fichero de entrega y
Se ha añadido un fichero de objetivos que no …
> añadido Germán Castro

- objetivos/AntonioAlcalaMartinez.md
- proyectos/hito-0.md
Corresponde al hito 0 
https://github.com/AntonioAlcM/IV-17-18/blob/master/objetivos/AntonioAlcalaMartinez.md
Entego el archivo hito-0.md actualizado y en objetivos entrego la lista de objetivos de la practica 0 y el repositorio donde se puede ver las capturas de pantalla
https://github.com/AntonioAlcM/IV-17-18/blob/master/proyectos/hito-0.md
https://github.com/AntonioAlcM/IV-17-18/blob/master/objetivos/AntonioAlcalaMartinez.md
> Practica 0

- objetivos/AndresGallardoMolina.md
- proyectos/hito-0.md
[Objetivos] (https://github.com/Maverick94/IV-17-18/blob/master/objetivos/AndresGallardoMolina.md)
He realizado un fork del repositorio principal. Tras crear mi repositorio individual, he actualizado la 
información requerida en el repositorio principal. Dicha actualización es este *pull request*
[Objetivos] (https://github.com/Maverick94/IV_Proyecto/milestones)
> Entrega del hito 0

- objetivos/ManuelCasadoVergara.md
- proyectos/hito-0.md
o
[Fichero de objetivos](https://github.com/cvlolo/IV-17-18/blob/master/objetivos/ManuelCasadoVergara.md)
Se entrega el enlace al repositorio de mi proyecto así como los objetivos del hito y tema 1, incluyendo un enlace a mi repositorio con los ejercicios
Se cierran los issues correspondientes  a los ejercicios entregados así como el issue de realización de objetivos.
[Primer issue](https://github.com/cvlolo/Ejercicios-IV/issues/1)
[Segundo issue](https://github.com/cvlolo/Ejercicios-IV/issues/2)
[Tercer …
> Se añaden los objetivos y apunto mi repositorio en hito0

- objetivos/LuisLiñanVillafranca.md
Corresponde al hito <incluir número del hito aquí>
o
*Borrar lo que no corresponda*
** Y estas notas también **
> Añadido del fichero de objetivos.

- objetivos/AntonioJesusPelaezPriego.md
- proyectos/hito-0.md
[Enlace a los objetivos correspondientes a este hito](https://github.com/ajpelaez/IV-17-18/blob/master/objetivos/AntonioJesusPelaezPriego.md)
Entregado fichero de objetivos completo, junto con el enlace al repositorio de mi proyecto agregado en el fichero hito0.
[Enlace repo proyecto](https://github.com/ajpelaez/IV-Proyecto)
[Enlace repo ejercicios](https://github.com/ajpelaez/IV-Ejercicios)
> Entrega de fichero de objetivos

- objetivos/AlvaroMunozGarcia.md
- proyectos/hito-0.md
https://github.com/alvaromgs/IV-17-18/blob/master/objetivos/AlvaroMunozGarcia.md
Añadidos objetivos, enlace a mi repositorio y versión de la actualización
https://github.com/alvaromgs/proyectoIV-1718/milestones?state=closed
> Objetivos y enlace al repositorio

- objetivos/MiriamMengibarRodriguez.md
- proyectos/hito-0.md
o
[Objetivos](https://github.com/mirismr/IV-17-18/blob/master/objetivos/MiriamMengibarRodriguez.md)
Entrega de los objetivos y enlace a mi proyecto personal.
https://github.com/mirismr/proyectoIV17-18/milestone/1
> Fichero objetivos hito0

- objetivos/AlvaroCarmonaOliva.md
- proyectos/hito-0.md
[Entrega de fichero de objetivos](https://github.com/alvarocarmona6/IV-17-18/blob/master/objetivos/AlvaroCarmonaOliva.md)
Se entrega el enlace de mi proyecto y también mis objetivos incluyendo  los enlaces de los ejercicios del tema 1.
enlaces a los issues de mis ejercicios
[primer issue](https://github.com/alvarocarmona6/Ejercicios-IV/issues/1)
[segundo issue](https://github.com/alvarocarmona6/Ejercicios-IV/issues/2)
[tercer issue](https://github.com/alvarocarmona6/Ejercicios-IV/issues/3)
[cuarto …
> Entrega hito0

- proyectos/hito-0.md
[Objetivos](https://github.com/cvlolo/IV-17-18/blob/master/objetivos/ManuelCasadoVergara.md)
El archivo hito0.md no contenía mi repositorio
> Corrección de archivo hito0

- objetivos/RafaelMedinaFacal.md
https://github.com/Medfac9/IV-17-18/blob/master/objetivos/RafaelMedinaFacal.md
Entrega de los objetivos completados de la primera práctica.
> Objetivos completados

- proyectos/hito-0.md
https://github.com/alvaromgs/IV-17-18/blob/master/objetivos/AlvaroMunozGarcia.md
Añado de nuevo el enlace a mi repositorio que se había borrado.
https://github.com/alvaromgs/proyectoIV-1718/milestones?state=closed
> Añadido nuevamente enlace al repositorio

- proyectos/hito-0.md
> Modificación hito 0

- objetivos/AlbertoDelRioAguilar.md
- proyectos/hito-0.md
o
[objetivos/AlbertoDelRioAguilar](https://github.com/berbus/IV-17-18/blob/master/objetivos/AlbertoDelRioAguilar.md)
Creados los repositorios para ejercicios y proyecto (+web). 
Modificados los archivos objetivos/AlbertoDelRioAguilar.md y proyectos/hito-0.md
> Entrega práctica 0

- objetivos/DavidSanchezMontes.md
- proyectos/hito-0.md
[Objetivos David](https://github.com/Anixo/IV-17-18/blob/master/objetivos/DavidSanchezMontes.md)
Se ha entregado el fichero correspondiente a objetivos y modificado el fichero del hito 0 con mi repositorio del proyecto.
https://github.com/Anixo/ProyectoIV/milestones
> Subida de objetivos y proyecto

- objetivos/ManuelLopezAceituno.md
- proyectos/hito-0.md
Corresponde al hito Hito0
o
https://github.com/manuellopez92/IV-17-18/blob/master/objetivos/ManuelLopezAceituno.md
Entrega del fichero de objetivos del hito0
https://github.com/manuellopez92/ProyectoIV/milestone/1
> Objetivos Hito0

- objetivos/MarioFernandezGomez.md
- proyectos/hito-0.md
Añadiendo los objetivos de la sesion 0
> Añadido objetivos Mario Fernández Gómez

- objetivos/LuisLiñanVillafranca.md
- proyectos/hito-0.md
[Enlace a objetivos de este hito](https://github.com/lulivi/IV-17-18/blob/master/objetivos/LuisLi%C3%B1anVillafranca.md)
Finalización del hito 0
> Completado objetivo de creación de repo del proyecto

- objetivos/SergioCervillaOrtega.md
[Objetivos Sergio Cervilla](https://github.com/Cerv1/IV-17-18/blob/master/objetivos/SergioCervillaOrtega.md)
He añadido mis objetivos
> Completados objetivos de la primera semana

- objetivos/MarioFernandezGomez.md
> Añado objetivo: explicacion de la configuracion

- objetivos/AdrianMorenteGabaldon.md
- objetivos/JJ.md
[objetivos/AdrianMorenteGabaldon.md](https://github.com/adrianmorente/IV-17-18/objetivos/AdrianMorenteGabaldon.md)
Entregué el archivo *hito-0.md*, y esta vez añado el fichero *objetivos/AdrianMorenteGabaldon.md*.
> Editando entrega. Añado fichero de objetivos

- objetivos/GuillermoMuriel.md
- proyectos/hito-0.md
Corresponde al hito <incluir número del hito aquí>
o
*Borrar lo que no corresponda*
** Y estas notas también **
> Pull Req Guillermo Muriel (como no, con retraso)

- proyectos/hito-0.md
https://github.com/guillesiesta/IV-17-18/blob/master/objetivos/GuillermoMuriel.md
Entrega del hito 0 por segunda vez.
> Actualizada versión segunda entrega hito 0

- objetivos/AntonioJesusPelaezPriego.md
- proyectos/hito-0.md
Entrega de la práctica corregida de acuerdo con las indicaciones del profesor.
https://github.com/ajpelaez
> Corrección hito0

- objetivos/MiriamMengibarRodriguez.md
https://github.com/mirismr/IV-17-18/blob/master/objetivos/MiriamMengibarRodriguez.md
Entrega del fichero de objetivos
https://github.com/mirismr/ejerciciosIV/milestone/1
> Fichero de objetivos

- objetivos/Medfac9.md
- objetivos/RafaelMedinaFacal.md
Entrega de los objetivos cumplidos del hito 0
> Objetivos del hito 1

- objetivos/AntonioAlcM.md
[Objetivos](https://github.com/AntonioAlcM/IV-17-18/blob/master/objetivos/AntonioAlcM.md)
Entrega de los objetivos de la segunda semana
> añadiendo objetivos segunda semana

- objetivos/ajpelaez.md
[Enlace a los objetivos](https://github.com/ajpelaez/IV-17-18/blob/master/objetivos/ajpelaez.md)
Entrega de los objetivos del tema 1
[Entrega ej 1,2,3](https://github.com/ajpelaez/IV-Ejercicios/issues/1)
[Entrega ej 4](https://github.com/ajpelaez/IV-Ejercicios/issues/2)
[Entrega ej 5](https://github.com/ajpelaez/IV-Ejercicios/issues/3)
[Entrega ej 6](https://github.com/ajpelaez/IV-Ejercicios/issues/4)
> Entrega objetivos tema1

- objetivos/Medfac9.md
He modificado los objetivos y añadido enlaces que muestren el cumplimiento de dichos objetivos. Los ejercicios están realizados completos pero no están subidos enteros aun ya que están en el pc de casa y se me olvidó subirlos.
Modificación de nombre del fichero -> https://imgur.com/R8KMnr3
Ejercicios -> https://github.com/Medfac9/Ejercicios_IV/blob/master/Tema%201.md
> Modificación de objetivos

- objetivos/guillesiesta.md
Entrega de fichero de objetivos
Entrega del fichero de objetivos actualizado. Enlace con los ejercicios resueltos de la semana 2 añadido.
> Entrega del fichero de objetivos. Ya con varios ejercicios resueltos.

- objetivos/franfermi.md
https://github.com/franfermi/IV-17-18/blob/master/objetivos/franfermi.md
Entrega del fichero de objetivos.
https://github.com/franfermi/Infraestructura-Virtual_IV/milestone/2
https://github.com/franfermi/Infraestructura-Virtual_IV/issues/6
https://github.com/franfermi/Infraestructura-Virtual_IV/issues/7
https://github.com/franfermi/Infraestructura-Virtual_IV/issues/8
> Subida de objetivos

- objetivos/AntonioAlcM.md
[Enlace](https://github.com/AntonioAlcM/IV-17-18/blob/master/objetivos/AntonioAlcM.md)
Entrega de los ejercicios del tema 1
> añadido la resolución de los ejercicios del tema 1

- proyectos/hito-1.md
https://github.com/alvarocarmona6/IV-17-18/blob/master/objetivos/alvarocarmona6.md
Actualizo el fichero de hito1 con mi enlace del proyecto
[primer hito](https://github.com/alvarocarmona6/ProyectoIV/milestone/1)
[segundo hito](https://github.com/alvarocarmona6/ProyectoIV/milestone/2)
[tercer hito](https://github.com/alvarocarmona6/ProyectoIV/milestone/3)
[cuarto hito](https://github.com/alvarocarmona6/ProyectoIV/milestone/4)
[quinto hito](https://github.com/alvarocarmona6/ProyectoIV/milestone/5)
> Subo hito1

- proyectos/hito-1.md
o
Entrega del Hito1
https://github.com/manuellopez92/ProyectoIV/milestone/2
> Entrega Hito1

- objetivos/MagicJHC10.md
https://github.com/MagicJHC10/IV-17-18/blob/master/objetivos/MagicJHC10.md
Entrega de los objetivos de la segunda semana
> Objetivos de la segunda semana

- proyectos/hito-1.md
[Objetivos](https://github.com/cvlolo/IV-17-18/blob/master/objetivos/cvlolo.md)
Subida del hito 1
https://github.com/cvlolo/Ejercicios-IV/issues/5
https://github.com/cvlolo/Ejercicios-IV/issues/6
https://github.com/cvlolo/IV-Proyecto/issues/1
> Subo el hito 1

- objetivos/manuellopez92.md
https://github.com/manuellopez92/IV-17-18/blob/master/objetivos/manuellopez92.md
Actualización del fichero de objetivos con los objetivos del Hito1
https://github.com/manuellopez92/ProyectoIV/milestone/2
> Entrega de Objetivos

- proyectos/hito-1.md
https://github.com/franfermi/IV-17-18/blob/master/objetivos/franfermi.md
correspondiente.  
Subida de hito-1
https://github.com/franfermi/Infraestructura-Virtual_IV/milestone/2
franfermi/Infraestructura-Virtual_IV#6
franfermi/Infraestructura-Virtual_IV#7
franfermi/Infraestructura-Virtual_IV#8
> Entrega hito-1

- proyectos/hito-1.md
correspondiente.   
Subida del hito 1. Descripción básica y técnica del proyecto.
https://github.com/guillesiesta/ProjectX/issues?q=is%3Aissue+is%3Aclosed
https://github.com/guillesiesta/ProjectX/milestones
> Subida del hito 1

- proyectos/hito-1.md
Corresponde al hito <1>
[objetivos](https://github.com/AntonioAlcM/IV-17-18/blob/master/objetivos/AntonioAlcM.md)
Entrega del hito 1 y corrección de errores de los pull request
https://github.com/AntonioAlcM/IV-17-18/blob/master/proyectos/hito-1.md
[milestone](https://github.com/AntonioAlcM/ProyectoIV17-18/milestone/1)
[issues](https://github.com/AntonioAlcM/ProyectoIV17-18/issues/1)
> Entrega de hito 1

- sesiones/semana-03.md
Corregido el titulo del final de la semana03
> Arreglado titulo

- objetivos/JaimeCasoOnzain.md
[Mis objetivos](https://github.com/JJ/IV-17-18/blob/master/objetivos/JaimeCasoOnzain.md)
[Mi hito](https://github.com/jimcase/IV-17-18-Proyectos)
Desarrollo de la segunda sesión, se trata de pensar o elegir un proyecto que se irá elaborando durante el año, creando los hitos para organizar el trabajo en el mismo. Lo esencial en este hito es entender qué tipo de proyectos se deben plantear para esta asignatura, describirlo correctamente en el repositorio en GitHub y documentar el proyecto elegido y los pasos que se van a dar en el mismo. …
> Subida objetivos

- proyectos/hito-1.md
Añadida mi parte al fichero hito-1.md con el repositorio del proyecto actualizado. 
He cerrado el issue #2
> Entrega del Hito 1.

- objetivos/Cerv1.md
- objetivos/SergioCervillaOrtega.md
[Mis objetivos de esta semana](https://github.com/Cerv1/IV-17-18/blob/master/objetivos/Cerv1.md)
Terminando los objetivos semanales.
> Añadidos objetivos de esta semana

- objetivos/JuanMartinQuiros.md
- objetivos/marquirj.md
y
https://github.com/marquirj/IV-17-18/blob/master/objetivos/marquirj.md
* [X ] He leído el guión del hito
* [ X] He actualizado con la última versión del fichero de entrega y
* [ X] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
* [ X] He actualizado con la última versión del fichero de entrega y
> Entrega hito y documentación

- proyectos/hito-1.md
https://github.com/dialpa/IV-17-18/blob/master/objetivos/dialpa.md
Entrega del hito 1
https://github.com/dialpa/IV-Proyecto/issues
> Entrega del hito 1

- objetivos/patamimbre.md
- proyectos/hito-1.md
https://github.com/patamimbre/IV_Trabajos
* [ X ] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
* [ X ] He actualizado con la última versión del fichero de entrega y
> completados objetivos

- proyectos/hito-1.md
Entrega del hito 1
[Milestone del proyecto para el hito 1](https://github.com/lulivi/bot-calendario-telegram/milestone/2)
[Milestone de la autoevaluación correspondiente al hito 1](https://github.com/lulivi/autoevaluacion-IV/milestone/2)
> Completado hito 1

- objetivos/lulivi.md
[fichero de objetivos](https://github.com/lulivi/IV-17-18/blob/master/objetivos/lulivi.md#otros-objetivos)
Añadido objetivo de hacer un pull request a una compañera
> Añadido objetivo de última hora

- proyectos/hito-1.md
[Objetivos](https://github.com/jimcase/IV-17-18/blob/master/objetivos/JaimeCasoOnzain.md)
Desarrollo de la sesión 2, se trata de pensar o elegir un proyecto que se irá elaborando durante el año, creando los hitos para organizar el trabajo en el mismo. Lo esencial en este hito es entender qué tipo de proyectos se deben plantear para esta asignatura, describirlo correctamente en el repositorio en GitHub y documentar el proyecto elegido y los pasos que se van a dar en el mismo.
[Issue](https://github.com/jimcase/IV-17-18-Proyectos/issues?q=is%3Aissue+is%3Aclosed) …
> Correccion issue

- objetivos/Anixo.md
https://github.com/Anixo/IV-17-18/blob/master/objetivos/Anixo.md
Actualizado los objetivos añadiendo los ejercicios del tema.
> Actualizado objetivos

- proyectos/hito-1.md
[Enlace](https://github.com/ainokila/IV-17-18/blob/master/objetivos/ainokila.md)
correspondiente.
Realizo la entrega de los objetivos y proyecto actualizado, asi como los ejercicios propuestos
[Hito 1] (https://github.com/ainokila/IV-17-18/milestone/1)
> Correccion hito 1

- objetivos/Maverick94.md
https://github.com/JJ/IV-17-18/blob/master/objetivos/Maverick94.md
Actualización de los objetivos. En concreto, he linkado hacia el repositorio donde tengo 
desarrollados los ejercicios
> Actualización de objetivos

- proyectos/hito-1.md
Corresponde al hito <1>
<https://github.com/JJ/IV-17-18/blob/master/objetivos/marquirj.md>
* [X ] He leído el guión del hito
* [ X] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [ X] Si estoy enviando otra versión porque no pasó los tests la
Entrega de los ejercicios y objetivos de la segunda sesión.
<https://github.com/marquirj/ProyectoSkull>
> Cambio de versión

- objetivos/josegob.md
[Objetivos](https://github.com/josegob/IV-17-18/blob/master/objetivos/josegob.md)
Entrege de los objetivos de la tercera semana
> Añadidos objetivos tercera semana

- objetivos/terceranexus6.md
[Enlace](https://github.com/terceranexus6/IV-17-18/blob/master/objetivos/terceranexus6.md) a los objetivos correspondientes a este hito.
Incluyo los objetivos a cumplir en esta sesión.
> añado objetivos

- proyectos/hito-2.md
Entrega del hito 2 donde se ha añadido entre otras cosas la IC con Travis
[Hito 2](https://github.com/josegob/IV-Proyecto/milestone/2)
- [Modificado README](https://github.com/josegob/IV-Proyecto/issues/2)
- [Makefile](https://github.com/josegob/IV-Proyecto/issues/4)
- [Configurar IC](https://github.com/josegob/IV-Proyecto/issues/5)
- [Objetivos completados](https://github.com/josegob/IV-Proyecto/issues/3)
> Añadido Repo Hito 2 #150

- objetivos/cvlolo.md
[Objetivos](https://github.com/cvlolo/IV-17-18/blob/master/objetivos/cvlolo.md)
Objetivos de la semana 3
> Subo los objetivos de la semana 3

- objetivos/franfermi.md
Subida de los objetivos de la tercera semana de clase.
> Subida objetivos 3 sesión

- objetivos/lulivi.md
Realización de algunos de los objetivos del hito 2 y añadido de algunos otros
> Añadidos objetivos del hito 2

- objetivos/ajpelaez.md
[Enlace a los objetivos correspondientes a este hito](https://github.com/ajpelaez/IV-17-18/blob/master/objetivos/ajpelaez.md)
Entrega del fichero de objetivos actualizado
> Objetivos actualizados

- proyectos/hito-2.md
Entrega del hito número 2
Hito cerrado --> https://github.com/Medfac9/Proyecto_IV/milestone/2 
Issues cerradas --> https://github.com/Medfac9/Proyecto_IV/issues/5
https://github.com/Medfac9/Proyecto_IV/issues/3
https://github.com/Medfac9/Proyecto_IV/issues/4
https://github.com/Medfac9/Proyecto_IV/issues/2
> Actualización hito2

- objetivos/guillesiesta.md
Actualización del fichero de objetivos. Aún no está lo suficientemente completo. Actualizado final a la espera.
> Actualización del fichero de objetivos

- objetivos/MagicJHC10.md
https://github.com/MagicJHC10/IV-17-18/blob/master/objetivos/MagicJHC10.md
Entrego los objetivos de la cuarta semana
> Subo objetivos de la cuarta semana

- objetivos/pmolinag.md
https://github.com/pmolinag/IV-17-18/blob/master/objetivos/pmolinag.md
Entrega de los objetivos correspondientes al 3 hito.
> Objetivos 3 hito. 

- proyectos/hito-2.md
correspondiente.   
Entrega al Hito 2
https://github.com/Maverick94/IV_Proyecto/milestones
> Entrega del hito 2

- objetivos/AntonioAlcM.md
[Enlace a los objetivos](https://github.com/AntonioAlcM/IV-17-18/blob/master/objetivos/AntonioAlcM.md)
Completado todos los objetivos del hito 2
> Completado todos los objetivos

- proyectos/hito-2.md
Entrega del enlace al proyecto con las actualizaciones requeridas por el hito 2
https://github.com/AntonioAlcM/ProyectoIV17-18/milestone/2
https://github.com/AntonioAlcM/ProyectoIV17-18/issues/2
https://github.com/AntonioAlcM/ProyectoIV17-18/issues/3
> Actualización del proyecto con integración continua #150 y test

- proyectos/hito-2.md
[Enlace a los objetivos correspondientes al hito](https://github.com/ajpelaez/IV-17-18/blob/master/objetivos/ajpelaez.md)
Se ha añadido el enlace a mi repo donde esta contenido el proyecto, en el cual se ha desarrollado siguiendo la metodología de TDD, además se ha agregado en este integración continua con Travis.
[Ejercicio 2 - Empezar con TDD](https://github.com/ajpelaez/IV-Proyecto/issues/3)
[Unificar los test unitarios en un grupo de tests con descripciones](https://github.com/ajpelaez/IV-Proyecto/issues/4)
[Terminar tests y añadir requeriments.txt para la herramienta pip](https://github.com/ajpelaez/IV-Proyecto/issues/5) …
> Añadido enlace a mi repo para el hito 2

- objetivos/franfermi.md
Entrega de los objetivos de la última semana de entrega y enlace a los ejercicios realizados del tema 2.
> Subida de objetivos segunda semana junto con enlace a ejercicios tema 2

- objetivos/alvaromgs.md
- proyectos/hito-2.md
https://github.com/alvaromgs/IV-17-18/blob/master/objetivos/alvaromgs.md
Añado enlace a mi proyecto en el hito 2 y actualizo los objetivos
https://github.com/alvaromgs/proyectoIV-1718/issues?q=is%3Aissue+is%3Aclosed+milestone%3A%22Hito+2%22
> Añado hito 2 y objetivos

- objetivos/ainokila.md
- proyectos/hito-2.md
https://github.com/ainokila/IV-17-18/blob/master/objetivos/ainokila.md
Entrega del Hito 2 de la asignatura
https://github.com/ainokila/IV-17-18/issues?q=is%3Aissue+is%3Aclosed
> Entrega hito 2

- proyectos/hito-2.md
https://github.com/franfermi/IV-17-18/blob/master/objetivos/franfermi.md
Entrega sobre el hito-2 del proyecto.
> Subida hito-2 closes #12

- objetivos/guillesiesta.md
Entrega de fichero de objetivos
Entrega de todos los ejercicios correspondientes al hito 2 y fichero de objetivos actualizado
> Todos los ejercicios hechos correspondientes a hito 2

- objetivos/adrianmorente.md
- proyectos/hito-2.md
o
[objetivos/adrianmorente.md](https://github.com/adrianmorente/IV-17-18/blob/master/objetivos/adrianmorente.md)
Termino el hito 2 y entrego el fichero de objetivos y el enlace a mi repositorio donde se ha llevado a cabo todo el trabajo.
> Entrego el hito 2 y el fichero de objetivos

- proyectos/hito-2.md
correspondiente.   
Entrega del hito 2. Tests creados y pasados en proyecto propio con Travis.
https://github.com/guillesiesta/ProjectX/issues/3
https://travis-ci.org/guillesiesta/ProjectX/builds/288239107
> Entregado hito 2 Guillermo Muriel

- objetivos/Anixo.md
- proyectos/hito-2.md
Se entrega el enlace al repositorio donde se ha añadido integración continua al proyecto
https://github.com/Anixo/ProyectoIV/milestone/3?closed=1
> Añadido repositorio

- proyectos/hito-2.md
Corresponde al hito <2>
<Entrega del hito 2>
https://github.com/MagicJHC10/Proyecto-IV/issues/6
https://github.com/MagicJHC10/Proyecto-IV/issues/5
https://github.com/MagicJHC10/Proyecto-IV/issues/4
https://github.com/MagicJHC10/Proyecto-IV/issues/3
https://github.com/MagicJHC10/Proyecto-IV/issues/2
> Subo hito 2

- objetivos/alvarocarmona6.md
- proyectos/hito-2.md
[repo](https://github.com/alvarocarmona6/ProyectoIV)
Subo mi hito 2
https://github.com/alvarocarmona6/ProyectoIV/issues/5
https://github.com/alvarocarmona6/ProyectoIV/issues/6
https://github.com/alvarocarmona6/ProyectoIV/issues/4
https://github.com/alvarocarmona6/ProyectoIV/issues/3
https://github.com/alvarocarmona6/ProyectoIV/issues/2
> Subo mi hito 2

- objetivos/MagicJHC10.md
https://github.com/MagicJHC10/IV-17-18/blob/master/objetivos/MagicJHC10.md
Entrega de Objetivos
> Actualizo fichero de objetivos

- proyectos/hito-2.md
Añadido enlace al proyecto para el hito 2
https://github.com/mirismr/proyectoIV17-18/milestone/3?closed=1
> Añadido proyecto hito2

- objetivos/mirismr.md
https://github.com/mirismr/IV-17-18/blob/master/objetivos/mirismr.md
Entrega fichero de objetivos del hito 2
https://github.com/mirismr/ejerciciosIV/milestone/2?closed=1
> Fichero objetivos hito 2

- objetivos/Cerv1.md
- proyectos/hito-2.md
[Mis objetivos](https://github.com/JJ/IV-17-18/blob/master/objetivos/Cerv1.md)
Terminado hito 2 y los objetivos
[Issue 4](https://github.com/Cerv1/IV-Project/issues/4) e [Issue 5](https://github.com/Cerv1/IV-Project/issues/5)
> Terminando sesión constituida de hito 2 y objetivos

- objetivos/cvlolo.md
- proyectos/hito-2.md
correspondiente.
[Enlace](https://github.com/cvlolo/IV-17-18/blob/master/objetivos/cvlolo.md)
Fichero de objetivos e hito 2
https://github.com/cvlolo/Ejercicios-IV/milestone/2?closed=1
https://github.com/cvlolo/IV-Proyecto/milestone/2
> Subo objetivos semana 4 y tema 2

- objetivos/carlillostole.md
https://github.com/JJ/IV-17-18/blob/master/objetivos/carlillostole.md
Objetivos de la semana subidos y enlace a los Ejercicios del TEMA 2.
> Objetivos carlillostole

- proyectos/hito-2.md
Entrega del hito 2: makefile, travis.yml, y requirements.txt. Y los tests.
carlillostole/proyectoIV17-18#1
carlillostole/proyectoIV17-18#3
carlillostole/proyectoIV17-18#2
carlillostole/proyectoIV17-18#4
carlillostole/proyectoIV17-18#5
carlillostole/proyectoIV17-18#6
carlillostole/proyectoIV17-18#7
carlillostole/proyectoIV17-18#8
carlillostole/proyectoIV17-18#9
> Entrega hito2

- objetivos/manuellopez92.md
Entrega de los objetivos del hito2
https://github.com/manuellopez92/ProyectoIV/milestone/3
> Objetivos Hito2

- objetivos/lulivi.md
Entrega de fichero de objetivos correspondiente al hito 2
Entrega del fichero de objetivos para la posterior entrega del hito
> Completados objetivos del hito 2

- proyectos/hito-2.md
[Objetivos de hito 2](https://github.com/lulivi/IV-17-18/blob/master/objetivos/lulivi.md)
Entrega del hito 2
[Milestone del proyecto](https://github.com/lulivi/bot-calendario-telegram/milestone/3?closed=1)
[issue de creación de módulos](https://github.com/lulivi/bot-calendario-telegram/issues/8)
[issue de creación y configuración de setup.py](https://github.com/lulivi/bot-calendario-telegram/issues/7)
[issue de creación de .travis.yml](https://github.com/lulivi/bot-calendario-telegram/issues/9)
[issue de corrección de errores](https://github.com/lulivi/bot-calendario-telegram/issues/10)
[Milestone de …
> Entrega de hito 2

- objetivos/Medfac9.md
Entrega de los primeros objetivos cumplidos
> Objetivos hito 3

- objetivos/josegob.md
https://github.com/josegob/IV-17-18/blob/master/objetivos/josegob.md
Entrega de ficheros objetivos
> Añadidos objetivos quinta semana

- objetivos/CarlosSanchez.md
Corresponde al hito <incluir número del hito aquí>
o
*Borrar lo que no corresponda*
** Y estas notas también **
> Objetivos Tema 0

- objetivos/mariofg92.md
- proyectos/hito-2.md
Y
<https://github.com/mariofg92/IV-17-18/blob/master/objetivos/mariofg92.md>
Objetivos e hito2
> Pull hito2

- proyectos/hito-2.md
> Nueva version

- sesiones/semana-05.md
> Actualización enlace a Paas

- objetivos/elsudano.md
[Lista de Objetivos cumplidos](https://github.com/elsudano/IV-17-18/blob/master/objetivos/elsudano.md#objetivos-semana-del-13-de-octubre-al-19-de-octubre-de-2017)
Se actualizan los objetivos de la semana 5 y 6 dejando los de la sexta semana sin marcar
> Actualización de los objetivos

- objetivos/Maverick94.md
https://github.com/Maverick94/IV-17-18/blob/master/objetivos/Maverick94.md
Subida objetivos
> Actualizacion objetivos

- objetivos/AntonioAlcM.md
[Enlace a los objetivos](https://github.com/AntonioAlcM/IV-17-18/blob/master/objetivos/AntonioAlcM.md)
Se ha entregado la actualización de los objetivos y el enlace a la resolución de los ejercicios del tema correspondiente
https://github.com/AntonioAlcM/IV-17-18/blob/master/objetivos/AntonioAlcM.md
https://github.com/AntonioAlcM/IV17-18-Autoevaluacion/tree/master/Tema3
> Añadidos los nuevos objetivos de octubre

- objetivos/franfermi.md
Entrega de los objetivos de la semana 5.
> Subida de objetivos sesión 5

- objetivos/franfermi.md
Entrega de los objetivos de la semana 6.
> Subida de objetivos sesión 6

- proyectos/hito-3.md
Entrega del hito 3 donde se ha añadido el despliegue en Heroku
[Hito 3](https://github.com/josegob/IV-Proyecto/milestone/3)
- [Modificar README](https://github.com/josegob/IV-Proyecto/issues/6)
- [Añadir archivos necesario para el despliegue del PaaS](https://github.com/josegob/IV-Proyecto/issues/7)
> Añadido repo hito 3 V3.5

- proyectos/hito-3.md
https://github.com/franfermi/IV-17-18/blob/master/objetivos/franfermi.md
correspondiente.  
Entrega del Hito-3 del proyecto de IV.
> Subida Hito3

- objetivos/ainokila.md
- proyectos/hito-3.md
https://github.com/ainokila/IV-17-18/blob/master/objetivos/ainokila.md
Entrega del hito 3 con el despliegue
https://github.com/ainokila/IV-17-18/issues?q=is%3Aissue+is%3Aclosed
> Entrega hito 3

- objetivos/carlillostole.md
https://github.com/JJ/IV-17-18/blob/master/objetivos/carlillostole.md
Objetivos subidos quinta semana.
> Objetivos quinta semana

- proyectos/hito-3.md
https://github.com/carlillostole/proyectoIV17-18
Entrega del hito 3,continuando con el proyecto.
carlillostole/proyectoIV17-18#1
carlillostole/proyectoIV17-18#3
carlillostole/proyectoIV17-18#2
carlillostole/proyectoIV17-18#4
carlillostole/proyectoIV17-18#5
carlillostole/proyectoIV17-18#6
carlillostole/proyectoIV17-18#7
carlillostole/proyectoIV17-18#8
carlillostole/proyectoIV17-18#9
carlillostole/proyectoIV17-18#10
carlillostole/proyectoIV17-18#11
carlillostole/proyectoIV17-18#12
carlillostole/proyectoIV17-18#13
carlillostole/proyectoIV17-18#14
carlillostole/proyectoIV17-18#15
carlillostole/proyectoIV17-18#16 …
> Proyecto hito3 subido

- objetivos/mirismr.md
https://github.com/mirismr/IV-17-18/blob/master/objetivos/mirismr.md
Entrega de los objetivos a cumplir en el tema 3
https://github.com/mirismr/ejerciciosIV/milestone/3
> Entrega objetivos tema 3

- objetivos/ajpelaez.md
[Fichero de objetivos](https://github.com/ajpelaez/IV-17-18/blob/master/objetivos/ajpelaez.md)
Entrega del fichero de objetivos, agregando los objetivos de la semana 4 y 5.
[Enlace a los ejercicios correspondientes al tema3](https://github.com/ajpelaez/IV-Ejercicios/blob/master/relaci%C3%B3n3-ejercicios.md)
> Agregados objetivos de la semana 4 y 5

- objetivos/patamimbre.md
- proyectos/hito-3.md
[objetivos patamimbre](https://github.com/JJ/IV-17-18/blob/master/objetivos/patamimbre.md)
* [] He actualizado con la última versión del fichero de entrega y
* [ X] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
En [](https://github.com/patamimbre/IV_Trabajos/blob/master/paas.md) se encuentran los ejercicios realizados de forma didáctica para crear una aplicación en heroku con ruby
> Objetivos patamimbre

- objetivos/alvaromgs.md
- proyectos/hito-3.md
https://github.com/alvaromgs/IV-17-18/blob/master/objetivos/alvaromgs.md
Añadidos objetivos de las últimas semanas y entrego hito 3
https://github.com/alvaromgs/proyectoIV-1718/issues?q=is%3Aissue+is%3Aclosed+milestone%3A%22Hito+3%22
> Añadidos objetivos y tercer hito

- proyectos/hito-3.md
https://github.com/alvarocarmona6/ProyectoIV
Subo mi Hito 3 
https://github.com/alvarocarmona6/ProyectoIV/milestone/3
>  Subo hito 3

- proyectos/hito-3.md
Corresponde al hito <3>
o
Entrego hito 3
https://github.com/MagicJHC10/Proyecto-IV/issues/7
https://github.com/MagicJHC10/Proyecto-IV/issues/8
https://github.com/MagicJHC10/Proyecto-IV/issues/9
> Subo hito 3

- objetivos/alvarocarmona6.md
https://github.com/alvarocarmona6/IV-17-18/blob/master/objetivos/alvarocarmona6.md
Subo mis objetivos
> Subo mis objetivos

- objetivos/MagicJHC10.md
<https://github.com/MagicJHC10/IV-17-18/blob/master/objetivos/MagicJHC10.md>
Entrega de los objetivos de este hito
> Entrega de los objetivos

- proyectos/hito-3.md
Subida del hito 3
[Hito 3](https://github.com/cvlolo/IV-Proyecto/milestone/3)
> Arreglando conflicto

- proyectos/hito-3.md
Despliegue de la app y corregir tests.
> añado proyecto

- objetivos/Anixo.md
https://github.com/Anixo/IV-17-18/blob/master/objetivos/Anixo.md
Se han añadido los objetivos correspondientes
> Añadido objetivos hito3

- objetivos/cvlolo.md
https://github.com/cvlolo/IV-17-18/blob/master/objetivos/cvlolo.md
Objetivos quinta semana
> Subo objetivos

- objetivos/Cerv1.md
- proyectos/hito-3.md
https://github.com/Cerv1/IV-17-18/blob/master/objetivos/Cerv1.md
Terminando este hito por completo
https://github.com/Cerv1/IV-Project/issues/6
> Añadiendo objetivos e hito

- objetivos/lulivi.md
- proyectos/hito-3.md
Completado el hito 3 configurando el despliegue de la aplicación
[Milestone 3](https://github.com/lulivi/bot-calendario-telegram/milestone/4)
[Issue 14](https://github.com/lulivi/bot-calendario-telegram/issues/14)
[Issue 15](https://github.com/lulivi/bot-calendario-telegram/issues/15)
> Completado fichero de objetivos y entrega del hito 3

- proyectos/hito-3.md
https://github.com/JJ/IV-17-18/blob/master/objetivos/AlbertoDelRioAguilar.md
Todo el hito 3, sólo porque se me había olvidado actualizar la parte del proyecto.
[Milestone hito 3](https://github.com/berbus/proyectoIV/milestone/4)
[Issue: Ficheros de configuración PaaS](https://github.com/berbus/proyectoIV/issues/12)
[Issue: Despliegue correcto](https://github.com/berbus/proyectoIV/issues/11)
[Issue: Descripción de la configuración en Github](https://github.com/berbus/proyectoIV/issues/10)
> Añadido enlace a proyectos (se me había olvidado)

- objetivos/CarlosSanchez.md
[Enlace](]https://github.com/CharlySM/IV-17-18/blob/master/objetivos/CarlosSanchez.md)
Objetivos tema 2
> Objetivos tema 2

- proyectos/hito-3.md
[Objetivos hito 3](https://github.com/elsudano/IV-17-18/blob/master/objetivos/elsudano.md#objetivos-semana-del-2-de-noviembre-al-7-de-noviembre-de-2017)
Se entrega el hito 3 para después volver a entregar una segunda versión por que no llego a cumplir todos los requisitos
[Hito 2]()
Lista de todos los Issues: [26](https://github.com/elsudano/MiddleWare_NextCloud/issues/26), [27](https://github.com/elsudano/MiddleWare_NextCloud/issues/27), [34](https://github.com/elsudano/MiddleWare_NextCloud/issues/34), [37](https://github.com/elsudano/MiddleWare_NextCloud/issues/37), …
> Entrega del hito 3

- objetivos/lulivi.md
Proposición de objetivos para este hito.
> Añadidos objetivos del hito 4

- objetivos/mariofg92.md
- proyectos/hito-3.md
y
https://github.com/mariofg92/IV-17-18/blob/master/objetivos/mariofg92.md
Hito 3 y objetivos.
> Hito 3 y objetivos

- objetivos/manuellopez92.md
Entrega de los objetivos correspondientes al hito 3
https://github.com/manuellopez92/ProyectoIV/milestone/4?closed=1
> Entrega Objetivos Hito3

- proyectos/hito-3.md
https://github.com/JJ/IV-17-18/blob/master/objetivos/manuellopez92.md
Entrega del repositorio del Hito3
https://github.com/manuellopez92/ProyectoIV/milestone/4?closed=1
> Entrega Hito3

- objetivos/guillesiesta.md
- proyectos/hito-3.md
Entrego el fichero de objetivos actualizado para posteriormente entregar el hito 3
> Actualizado fichero de objetivos

- objetivos/AntonioAlcM.md
[Enlace a la resolución de los ejercicios](https://github.com/AntonioAlcM/IV17-18-Autoevaluacion/tree/master/Tema4)
Entrega de los ejercicios correspondientes al hito IV
> Actualizando los objetivos y añadido los ejercicios

- objetivos/elsudano.md
[https://github.com/elsudano/IV-17-18/blob/master/objetivos/elsudano.md](https://github.com/elsudano/IV-17-18/blob/master/objetivos/elsudano.md)
He actualizado los objetivos para el hito 4 con los que he realizado y los que puedo realizar
> Añadiendo los objetivos del hito

- objetivos/Medfac9.md
> Objetivos hito 4

- objetivos/AntonioAlcM.md
- proyectos/hito-4.md
Entrega del hito 4 con despliege en dockerhub y Zeit
https://github.com/AntonioAlcM/tfg_ugr/issues?q=is%3Aissue+is%3Aclosed
> Entrega hito 4

- proyectos/ejercicio-1.md
https://github.com/marquirj/ProyectoSkull/pull/12
Entrega del ejercicio extra.
> añadiendo test adicionales

- proyectos/hito-1.md
- proyectos/hito-2.md
- proyectos/hito-3.md
Corresponde al hito <1, 2 y 3>
> Subo hitos del 1 al 3.

- proyectos/hito-4.md
hito 4
Subo hito 4
<
https://github.com/alvarocarmona6/ProyectoIV/milestone/4
> Subo hito 4

- objetivos/franfermi.md
Entrega de los objetivos de la semana 8 y 9
> Objetivos sesión 8 y 9

- objetivos/carlillostole.md
https://github.com/JJ/IV-17-18/blob/master/objetivos/carlillostole.md
Entrega de los objetivos del hito 4 y sus ejercicios correspondientes ( tema 4).
carlillostole/proyectoIV17-18#24
carlillostole/proyectoIV17-18#26
> objetivos hito4

- proyectos/hito-4.md
https://github.com/JJ/IV-17-18/blob/master/objetivos/franfermi.md
Entrega del hito 4 correspondiente a la asignatura IV
> Subida del hito 4

- objetivos/lulivi.md
- sesiones/README.md
- sesiones/semana-09.md
* Completado de casi todos los objetivos
* Arreglo en el nombre de un fichero
* Añadidas nuevas sesiones al readme de las sesiones
> Completado de algunos objetivos y corrección de errores en algunos ficheros

- objetivos/AntonioAlcM.md
[Enlace a la resolución de los ejercicios](https://github.com/AntonioAlcM/IV17-18-Autoevaluacion/tree/master/Tema4)
Actualización de los objetivos semana 9
> Subiendo objetivos semana 9

- objetivos/adrianmorente.md
- proyectos/hito-4.md
Entrego el hito 4, actualizando el README ilustrando lo realizado para este hito (configuración y despliegue en Docker, linkado con Github en Docker Hub y descarga de imagen completa con comando de Docker Hub.
[Hito 12](https://github.com/adrianmorente/PracticasIV/issues/12)
[Hito 13](https://github.com/adrianmorente/PracticasIV/issues/13)
> entrego hito 4

- objetivos/guillesiesta.md
Entrega de fichero de objetivos
Entrega del fichero de objetivos previo a la realización y entrega del hito 4
> actualizado fichero objetivos sesion 5

- objetivos/Cerv1.md
- proyectos/ejercicio-1.md
- proyectos/hito-4.md
Corresponde al hito 4 y entrega de fichero de objetivos 
https://github.com/Cerv1/IV-17-18/blob/master/objetivos/Cerv1.md
Añadiendo mi fichero de objetivos y el hito correspondiente
Colaboración para crédito extra: https://github.com/adrianmorente/PracticasIV/pull/16
https://github.com/Cerv1/IV-Project/issues/8
> Añadiendo mis objetivos y la práctica de esta semana

- proyectos/hito-4.md
He conseguido que se pueda desplegar la aplicación en las 2 plataformas Heroku y Zeit al mismo tiempo con un solo git push, de esta forma podemos comprobar el dockerfile y la aplicación en un PaaS
> Entrega del Hito 4

- objetivos/MagicJHC10.md
<https://github.com/MagicJHC10/IV-17-18/blob/master/objetivos/MagicJHC10.md>
<Entrega de los objetivos>
> Subo fichero de objetivos

- proyectos/hito-4.md
Entrega enlace hito 4 proyecto
https://github.com/mirismr/proyectoIV17-18/milestone/5
> hito 4 proyecto

- objetivos/mirismr.md
https://github.com/mirismr/IV-17-18/blob/master/objetivos/mirismr.md
Entrega fichero de objetivos
https://github.com/mirismr/ejerciciosIV/milestone/4
> fichero objetivos

- objetivos/Anixo.md
- proyectos/ejercicio-1.md
Corresponde al hito ejercicio1
Entrego el enlace del pull request aceptado
> Agregado ejercicio

- proyectos/ejercicio-1.md
Corresponde al hito IV
He añadido un test al código de  @AntonioAlcM 
https://github.com/AntonioAlcM/tfg_ugr/pull/17
> Añado un test al repo de AntonioAlcM

- objetivos/ajpelaez.md
https://github.com/ajpelaez/IV-17-18/blob/master/objetivos/ajpelaez.md
Entrega de los objetivos de las últimas semanas.
[Enlace al repositorio con los ejercicios de la asignatura](https://github.com/ajpelaez/IV-Ejercicios)
> Agregados objetivos de las últimas semanas

- objetivos/ainokila.md
- proyectos/hito-4.md
https://github.com/ainokila/IV-17-18/blob/master/objetivos/ainokila.md
Entrega hito 4 y desplegado servicio en zenit
https://github.com/ainokila/ProyectoIV/milestone/4
> Terminado hito 4

- proyectos/hito-4.md
correspondiente.   
Entrega del hito 4
https://github.com/guillesiesta/ProjectX
https://github.com/guillesiesta/ProjectX/issues?q=is%3Aissue+is%3Aclosed
> subida hito 4

- objetivos/lulivi.md
Entrega del fichero de objetivos para esta semana.
> Añadidos objetivos de la semana que entra

- objetivos/terceranexus6.md
- proyectos/hito-3.md
- proyectos/hito-4.md
[Objetivos](https://github.com/terceranexus6/IV-17-18/blob/master/objetivos/terceranexus6.md)
Comprender el uso de contenedores en el desarrollo de una aplicación, probar dockerhub, y añadirlo a mi proyecto.
- Añadir contenedor en el README
- Corregir json para que salga en /status
[Link al repo](https://github.com/terceranexus6/copylazyjacker)
> Añado proyecto 

- proyectos/hito-4.md
* [X ] He leído el guión del hito
* [ X] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [ X] He actualizado con la última versión del fichero de entrega y
* [ X] Si estoy enviando otra versión porque no pasó los tests la
Aplicación muy simple para entender el funcionamiento. Ahora hay que aplicarlo al nuevo proyecto real.
> hito 4 v0.1

- objetivos/josegob.md
https://github.com/josegob/IV-17-18/blob/master/objetivos/josegob.md
Entrega de ficheros objetivos
> Añadidos objetivos ultimo hito

- objetivos/Medfac9.md
Entrega de los objetivos del hito 5
> Objetivos hito 5

- proyectos/hito-5.md
Entrega del hito 5 donde se ha añadido el despliegue en un IaaS
[Hito 5](https://github.com/josegob/IV-Proyecto/milestone/5)
- [Modificar README](https://github.com/josegob/IV-Proyecto/issues/10)
- [Crear script automatizar tareas](https://github.com/josegob/IV-Proyecto/issues/13)
- [Crear archivo Ansible](https://github.com/josegob/IV-Proyecto/issues/14)
- [Crear archivo fabfile.py](https://github.com/josegob/IV-Proyecto/issues/11)
- [Crear archivo Vagrant](https://github.com/josegob/IV-Proyecto/issues/12)
> Añadido repo para hito 5

- objetivos/franfermi.md
Entrega de los objetivos de las últimas sesiones 10, 11, 12 y 13.
> Subida de objetivos entrega final

- proyectos/hito-5.md
Entrego hito 5
https://github.com/cvlolo/IV-Proyecto/milestone/5
> Subo ultimo hito

- proyectos/hito-5.md
[Objetivos](https://github.com/JJ/IV-17-18/blob/master/objetivos/franfermi.md)
correspondiente.  
Entrega final del proyecto de la asignatura IV.
[Hitos e issues](https://github.com/franfermi/Infraestructura-Virtual_IV/issues?q=is%3Aissue+is%3Aclosed)
> Subida de Hito 5

- objetivos/carlillostole.md
https://github.com/JJ/IV-17-18/blob/master/objetivos/carlillostole.md
Objetivos finales de la asignatura.
> Objetivos finales

- proyectos/hito-5.md
Corresponde al hito hito5
Entrega del último hito de la asignatura, aunque se sigue desarrollando el proyecto y actualizando archivos.
[Hitos e issues](https://github.com/carlillostole/proyectoIV17-18/issues?q=is%3Aissue+is%3Aclosed)
> Entrega hito5 carlillostole

- proyectos/hito-5.md
Corresponde al hito5
Subo mi hito 5
https://github.com/alvarocarmona6/ProyectoIV/milestone/5
>  Subo hito 5

- objetivos/Cerv1.md
- proyectos/hito-5.md
y
https://github.com/Cerv1/IV-17-18/blob/master/objetivos/Cerv1.md
Terminando el último hito de la asignatura
https://github.com/Cerv1/IV-Project/issues/9
> Finalizando el hito 5

- objetivos/alvarocarmona6.md
https://github.com/alvarocarmona6/IV-17-18/blob/master/objetivos/alvarocarmona6.md
Subo mis ficheros objetivos
>  Subo mis objetivos actualizados

- proyectos/hito-5.md
Entrega del hito 5
https://github.com/mirismr/proyectoIV17-18/milestone/6
> hito 5 enlace

- objetivos/AntonioAlcM.md
https://github.com/AntonioAlcM/IV-17-18/blob/master/objetivos/AntonioAlcM.md
Entrega de los ejercicios del tema 5 y 6
> Añadiendo los objetivos y los ejercicios

- proyectos/hito-5.md
Corresponde al hito <5>
<Entrega del hito 5>
https://github.com/MagicJHC10/Proyecto-IV/issues/14
https://github.com/MagicJHC10/Proyecto-IV/issues/15
https://github.com/MagicJHC10/Proyecto-IV/issues/16
> Subo Hito 5

- objetivos/guillesiesta.md
Entrega de fichero de objetivos
Entrega del fichero de objetivos correspondiente al hito 5
> Entrega fichero de objetivos

- objetivos/alvaromgs.md
- proyectos/hito-5.md
https://github.com/alvaromgs/IV-17-18/blob/master/objetivos/alvaromgs.md
Añado los últimos objetivos y entrego el hito 5
https://github.com/alvaromgs/proyectoIV-1718/issues?q=is%3Aissue+is%3Aclosed+milestone%3A%22Hito+5%22
> Añado objetivos y ultimo hito

- proyectos/hito-4.md
https://github.com/JJ/IV-17-18/blob/master/objetivos/manuellopez92.md
Entrega del Hito 4
https://github.com/manuellopez92/ProyectoIV/milestones
> Entrega del Hito4

- proyectos/hito-5.md
Subida hito
https://github.com/Maverick94/IV_Proyecto/milestone/6
> subida hito

- proyectos/hito-5.md
Corresponde al hito 5## Lista de comprobación para hitos (*borrar si no es un hito*)
Subida del Hito 5
https://github.com/Anixo/ProyectoIV/milestone/6?closed=1
> Subido hito5

- objetivos/lulivi.md
Entrega del fichero de objetivos
> Entrega del fichero de objetivos del hito 5

- proyectos/hito-5.md
Entrega del hito 5
[Hito 5](https://github.com/lulivi/bot-calendario-telegram/milestone/6)
[Creación del Vagrantfile](https://github.com/lulivi/bot-calendario-telegram/issues/19)
[Creación de los archivos de Ansible](https://github.com/lulivi/bot-calendario-telegram/issues/20)
[Creación del fabfile](https://github.com/lulivi/bot-calendario-telegram/issues/21)
> Entrega del hito 5

- objetivos/Anixo.md
https://github.com/JJ/IV-17-18/blob/master/objetivos/Anixo.md
Añado objetivos del hito 5
> Añadido objetivos

- objetivos/ajpelaez.md
- proyectos/hito-5.md
https://github.com/JJ/IV-17-18/blob/master/objetivos/ajpelaez.md
Actualización de los objetivos por cumplir de las últimas semanas.
> Actualización objetivos ultimas semanas

- proyectos/hito-5.md
Corresponde al hito <5>
* [X ] He leído el guión del hito
* [X ] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
Hito 5: despliegue de la aplicación en un IaaS (en mi caso azure) mediante Vagrant, Ansible y Fabric.
> 0.1 patamimbre añadido a hito 5

- proyectos/hito-5.md
> Cambio hito

- proyectos/hito-5.md
Subo el hito 5
https://github.com/alvarocarmona6/ProyectoIV/milestone/5
>  Subo mi hito5

- proyectos/hito-5.md
Entrega final del hito 5
https://github.com/cvlolo/IV-Proyecto/issues/19
https://github.com/cvlolo/IV-Proyecto/issues/20
https://github.com/cvlolo/IV-Proyecto/issues/21
https://github.com/cvlolo/IV-Proyecto/issues/22
https://github.com/cvlolo/IV-Proyecto/issues/23
https://github.com/cvlolo/IV-Proyecto/issues/24
https://github.com/cvlolo/IV-Proyecto/issues/25
https://github.com/cvlolo/IV-Proyecto/issues/26
> Subida final de Hito5

- proyectos/hito-5.md
Corresponde al hito5
https://github.com/ainokila/IV-17-18/blob/master/objetivos/ainokila.md
* [ X He actualizado con la última versión del fichero de entrega y
Entrega del hito5 con el despliegue en azure
https://github.com/ainokila/IV-17-18/issues
> Entrega hito5

- objetivos/manuellopez92.md
Entrega de los objetivos del último hito, el hito final
https://github.com/manuellopez92/ProyectoIV/milestones
> Entrega Objetivos Hito5

- objetivos/mariofg92.md
- proyectos/hito-4.md
y
* [ X] He leído el guión del hito
* [X ] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [ X] Si estoy enviando otra versión porque no pasó los tests la
* [X ] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
* [ X] He actualizado con la última versión del fichero de entrega y
Corrección enlaces
> Hito 4 y objetivos (corregido)

- proyectos/hito-5.md
https://github.com/JJ/IV-17-18/blob/master/objetivos/JaoChaos.md
Aquí entrego el hito 5, actualizando el fichero de objetivos y añadiendo el link del repositorio con los ejercicios de la asignatura.
A lo largo de la tarde mejoraré ciertos aspectos del proyecto.
https://github.com/JaoChaos/ejerciciosIV
> Hito 5 Final
